# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hostname", color = "(YW)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
desktop   = {icon = " ", name = "desktop", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(RD)"}
packages  = {icon = " ", name = "packages", color = "(RD)"}  # WARNING: Resource Intensive
shell     = {icon = " ", name = "shell", color = "(MA)"}
cpu       = {icon = " ", name = "cpu", color = "(RD)"}
disk_0    = {icon = " ", name = "disk", color = "(GN)"}
memory    = {icon = " ", name = "memory", color = "(YW)"}
battery   = {icon = " ", name = "battery", color = "(GN)"}
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # Try 'StatsOnTop' or 'ArtOnTop' for different layouts

#for all
stats_margin_top = 0  # Adjust as needed for spacing


#for smile
#stats_margin_top = 3  # Adjust as needed for spacing

#for mika
#stats_margin_top = 5  # Adjust as needed for spacing

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = true


#for sad
#path   = "/home/karan/Pictures/mikasa/sad.jpg" # Please only use absolute paths.
#scale  = 30
#margin = [1, 4, 1, 2] # Adjust margins as necessary for centering


#for smile
#path   = "/home/karan/Pictures/mikasa/smile.jpg" # Please only use absolute paths.
#scale  = 40
#margin = [1, 4, 1, 2] # Adjust margins as necessary for centering


#for mika
#path   = "/home/karan/Pictures/mikasa/mika.jpg" # Please only use absolute paths.
#scale  = 45
#margin = [1, 4, 1, 2] # Adjust margins as necessary for centering
    

#for Shy
#path   = "/home/karan/Pictures/mikasa/shy.png" # Please only use absolute paths.
#scale  = 28
#margin = [1, 4, 1, 2] # Adjust margins as necessary for centering


# For muscle
# path   = "/home/karan/Pictures/mikasa/muscles.jpg" # Please only use absolute paths.
# scale = 50
# margin = [5, 4, 5, 3]  # Adjust maFrgins as necessary for centering


# For mommy
# path   = "/home/karan/Pictures/mikasa/mommy.jpg" # Please only use absolute paths.
# scale = 25
# margin = [5, 4, 5, 3]  # Adjust margins as necessary for centering


# For pfp
# path   = "/home/karan/Pictures/mikasa/pfp.jpg" # Please only use absolute paths.
# scale  = 30
# margin = [1, 4, 1, 3]  # Adjust margins as necessary for centering


# For hotkasa
# path   = "/home/karan/Pictures/mikasa/hotkasa.jpg" # Please only use absolute paths.
# scale  = 55
# margin = [3, 4, 1, 3]  # Adjust margins as necessary for centering


# For cute
path   = "/Pictures/mikasa/cute.jpg" # Please only use absolute paths.
scale  = 30
margin = [1, 4, 1, 3]  # Adjust margins as necessary for centering


# For qt
# path   = "/home/karan/Pictures/mikasa/qt.jpg" # Please only use absolute paths.
# scale  = 40
# margin = [1, 4, 1, 2]  # Adjust margins as necessary for centering
